# Generated by Django 4.2.30 on 2026-05-24 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0007_post_created_real'),
    ]

    operations = [
        migrations.AddField(
            model_name='thread',
            name='restricted',
            field=models.BooleanField(default=False),
        ),
    ]
