# Generated by Django 4.2.30 on 2026-05-24 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0008_add_thread_restricted'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invite_code', models.CharField(blank=True, default='', help_text='If set, new users must enter this code to register. Leave empty to allow registration without a code.', max_length=128)),
            ],
            options={
                'verbose_name': 'Site Settings',
                'verbose_name_plural': 'Site Settings',
            },
        ),
    ]
